LABEL_ID2LABEL = {
    0: "O", 1: "B-PERSON", 2: "I-PERSON", 3: "B-ORG", 4: "I-ORG",
    5: "B-GPE", 6: "I-GPE", 7: "B-LOC", 8: "I-LOC",
    9: "B-NAT_REL_POL", 10: "I-NAT_REL_POL", 11: "B-EVENT", 12: "I-EVENT",
    13: "B-LANGUAGE", 14: "I-LANGUAGE", 15: "B-WORK_OF_ART", 16: "I-WORK_OF_ART",
    17: "B-DATETIME", 18: "I-DATETIME", 19: "B-PERIOD", 20: "I-PERIOD",
    21: "B-MONEY", 22: "I-MONEY", 23: "B-QUANTITY", 24: "I-QUANTITY",
    25: "B-NUMERIC_VALUE", 26: "I-NUMERIC_VALUE", 27: "B-ORDINAL", 28: "I-ORDINAL",
    29: "B-FACILITY", 30: "I-FACILITY",
}
